### ISSUE TITLE
[task] Create a countdown timer

### ISSUE THREAD

**Issue by ikorol3107** [Atlantis-Academy/frontend-study-ikorol#15]
**JavaScript в работе**

- Создать таймер обратного отсчета на сайте

_Для выполнения задания предварительно изучить темы:_ 

_1. Скрипты и время их выполнения. setTimeout и setInterval_
_2.  Работа с датами_

**Comment by TorinAsakura** [comment]
Не обязательно постоянно указывать, что ты что-то хочешь сделать "на веб-сайте"…

**Comment by ikorol3107** [comment]
хорошо, приняла.

**Comment by TorinAsakura** [comment]
> хорошо, приняла.

просто молча меняешь заголовок
этого было бы достаточно
