### ISSUE TITLE
[task] Add new functionality for the modal window

### ISSUE THREAD

**Issue by ikorol3107** [Atlantis-Academy/frontend-study-ikorol#20]
**JavaScript в работе**

- Добавить модальному окну новый функционал:  
   1 . Модальное окно появляется, когда пользователь проматывает веб-страницу до конца  
   2 . Модальное окно появляется через заданный промежуток времени

**Comment by TorinAsakura** [comment]
@ikorol3107 почему нет привязки к ПРу и в ПРе не указана задача?

**Comment by ikorol3107** [comment]
На эту задачу хочу делать отдельный ПР , т.к. тот который открыт сейчас - это создание модального окна , а в этой задаче я модифицирую окно.

**Comment by TorinAsakura** [comment]
@ikorol3107 Задача мелкая, столь незначительные вещи разве что в chore/ можно выносить…
