### ISSUE TITLE
[chore] Set up TS config

### ISSUE THREAD

**Issue by ikorol3107** [Atlantis-Academy/frontend-study-ikorol#25]
Настроить конфигурационный файл TS

**Comment by TorinAsakura** [comment]
> Установить TS и настроить конфигурационный файл TS

TS не устанавливается
@themetronome я вроде просил тебя подготовить показательную таску…

**Comment by ad21ewda1231dsa123das12** [comment]
> > Установить TS и настроить конфигурационный файл TS
> 
> TS не устанавливается
> @themetronome я вроде просил тебя подготовить показательную таску…

пример [таски по ts](https://github.com/Atlantis-Academy/frontend-study-themetronome/issues/22) уже готова, @ikorol3107 и @gochicus посмотрите и сделайте такие же таски по примеру, либо создам я

**Comment by ikorol3107** [comment]
@themetronome добавление файлов tsconfig.json в проект - это chore, а не refactor?
