### ISSUE TITLE
[chore] integrate ESLint into a project

### ISSUE THREAD

**Issue by ikorol3107** [Atlantis-Academy/frontend-study-ikorol#31]
### Какого рода задача?

- интегрировать в проект ESLint 

### Что и где будем менять?

- создание конфигурационного файла `.eslintrc.js`

### Укажите референс

- согласно плану ранее утвержденных задач:

1. Перевод проекта на Typescript
2. **Установка ESLint в проект**
3. Автоматизация проверок за счет хуков для Husky
4. Автоматизированный ESLint при мердже ПР в рабочую ветку через Github actions

**Comment by TorinAsakura** [comment]
> ### Какого рода задача?
> * интегрировать в проект ESLint
> 
> ### Что и где будем менять?
> * создание конфигурационного файла `.eslintrc.js`
> 
> ### Укажите референс
> * согласно плану ранее утвержденных задач:
> 
> 1. Перевод проекта на Typescript
> 2. **Установка ESLint в проект**
> 3. Автоматизация проверок за счет хуков для Husky
> 4. Автоматизированный ESLint при мердже ПР в рабочую ветку через Github actions

Причём тут план и референс?

**Comment by ikorol3107** [comment]
В референс нужно указывать в связи с чем создаётся задача, и,  т.к. у нас нигде отдельно не вынесен этот список задач, я его прописала здесь.
