### ISSUE TITLE
[task] functions creation

### ISSUE THREAD

**Issue by ikorol3107** [Atlantis-Academy/frontend-study-ikorol#5]
**Основы JavaScript**
Задание:

- Разбить существующий код на функции

- Создать функцию `showMyDB`, которая будет проверять свойство privat. Если стоит в позиции `false` - выводит в консоль главный объект программы

- Создать функцию `writeYourGenres` в которой пользователь будет 3 раза отвечать на вопрос "Ваш любимый жанр под номером `${номер по порядку}`". Каждый ответ записывается в массив данных `genres`

**Comment by TorinAsakura** [comment]
@ikorol3107 снова не заполнила поля
