### ISSUE TITLE
[feature] Create react-app

### ISSUE THREAD

**Issue by ikorol3107** [Atlantis-Academy/frontend-study-ikorol#59]
### С чем связан запрос на фичу?

- Создать react-приложение с функционалом "todo"-листа.

- Создать структуру react-приложения, используя JSX и стилизовать страницу, используя предложенные автором курса CSS-стили

### Расскажите как вы это себе видите

- развернуть проект в новом пакете `practice/my-diary`

- создать структуру приложения, используя JSX

- импортировать стили в проект

**Comment by TorinAsakura** [comment]
@ikorol3107 не нужно в заголовке задачи строчить поэму. Очень длинно, да ещё и с точкой
