### ISSUE TITLE
[chore] change the project structure

### ISSUE THREAD

**Issue by ikorol3107** [Atlantis-Academy/frontend-study-ikorol#63]
### Какого рода задача?
В `practice/my-diary` исправить структуру проекта

### Что и где будем менять?
скомпоновать компоненты согласно принципам SOLID (используя [пример](https://github.com/Atlantis-Lab/serenity/tree/feature/site/frontend)). 

- В UI-компонентах избавиться от хардкода
- Сделать зависимости на абстракциях
- Переделать всю стилизацию с использованием emotion

### Укажите референс
#59

**Comment by TorinAsakura** [comment]
@ikorol3107 Не обязательно оставлять мои комменты.
Во втором блоке нужно расписать что как и где ты будешь менять. Вкратце.

**Comment by TorinAsakura** [comment]
?
