### ISSUE TITLE
[task] Objects. OOPs Concepts

### ISSUE THREAD

**Issue by ikorol3107** [Atlantis-Academy/frontend-study-ikorol#7]
**Основы JavaScript**

Задание:

- У нас уже есть рабочее приложение, состоящее из отдельных функций. Представьте, что перед вами стоит задача переписать его так, чтобы все функции стали методами объекта `personalMovieDB`.  Такое случается в реальных продуктах при смене технологий или подхода к архитектуре программы.

- Создать метод `toggleVisibleMyDB` , который при вызове будет проверять свойство `privat`. Если оно `false` - он переключает его в `true`, если `true` - переключает в `false`. Протестировать вместе с `showMyDB`.

- В методе `writeYourGenres` запретить пользователю нажать кнопку "отмена" или оставлять пустую строку. Если он это сделал - возвращать его к этому же вопросу. После того, как все жанры введены - при помощи метода `forEach` вывести в консоль сообщения в таком виде: "Любимый жанр #(номер по порядку, начиная с 1) - это (название из массива)".

**Comment by TorinAsakura** [comment]
@ikorol3107 снова не заполнен сайдбар:
- assign - нужно ставить себя
