### ISSUE TITLE
[feature] update app design

### ISSUE THREAD

**Issue by TFK70** [Atlantis-Academy/frontend-study-ikorol#77]
### С чем связан запрос на фичу?

Обновить дизайн приложения:

![image](https://user-images.githubusercontent.com/62806448/116744548-e2bbef80-aa13-11eb-9f54-585ad084fd31.png)

### Расскажите как вы это себе видите

1. При наведении на задачу, помимо кнопки удаления должны быть уже реализованные кнопки "Like" и "Important"
2. В шапке приложения должен быть счетчик количества задач
3. Анимации и прочие динамические эффекты - на усмотрение
4. При нажатии на кнопку бургер меню в хедере, должно появляться меню с методами фильтрации задач
5. В остальном все должно соответствовать дизайну

**Comment by ikorol3107** [comment]
@TFK70 есть вопросы по таске:
1) у меня в кнопке "+ New task" есть захардкоженые значения, их можно оставить?:
```javascript
<Button
        width='fit-content'
        height='80px'
        position='relative'
        top='-45px'
        left='170px'
        fontSize='large'
        fontWeight='bold'
        color='white'
        backgroundColor='deepPurple'
        borderRadius='gigant'
        boxShadow='violet'
        onClick={() => {
          setInputStatus('visible')
          if (inputStatus === 'visible' && newNote !== '') {
            setNotes(addItem(notes, newNote))
            setNewNote('')
            setInputStatus('invisible')
          } else if (inputStatus === 'visible') {
            setInputStatus('invisible')
          }
        }}
      >
        <Space count={5} />
        {intl.formatMessage(messages.newTask)}
        <Space count={5} />
</Button>
```
2) Есть ли какой-то функционал у кнопки меню в Хэдере?

**Comment by TFK70** [comment]
> @TFK70 есть вопросы по таске:
> 
> 1. у меня в кнопке "+ New task" есть захардкоженые значения, их можно оставить?:
> 
> ```js
> <Button
>         width='fit-content'
>         height='80px'
>         position='relative'
>         top='-45px'
>         left='170px'
>         fontSize='large'
>         fontWeight='bold'
>         color='white'
>         backgroundColor='deepPurple'
>         borderRadius='gigant'
>         boxShadow='violet'
>         onClick={() => {
>           setInputStatus('visible')
>           if (inputStatus === 'visible' && newNote !== '') {
>             setNotes(addItem(notes, newNote))
>             setNewNote('')
>             setInputStatus('invisible')
>           } else if (inputStatus === 'visible') {
>             setInputStatus('invisible')
>           }
>         }}
>       >
>         <Space count={5} />
>         {intl.formatMessage(messages.newTask)}
>         <Space count={5} />
> </Button>
> ```
> 
> 1. Есть ли какой-то функционал у кнопки меню в Хэдере?

1. Не понял сути вопроса. Во-первых тут захардкоженных значений вроде как бы нет, просто компонент реализован иначе, чем другие. Во-вторых, конечно, делать конкретно так - не стоит, но местами подобное может быть необходимостью, и если без этого ничего не работает - то к чему это тогда убирать?
2. Да, там должно быть выдвижное меню, где можно выбрать метод фильтрации задач, таску обновил. Его дизайн - на усмотрение. Это может быть как [drawer](https://ant.design/components/drawer/), так и обычная модалка

**Comment by ikorol3107** [comment]
@TFK70 в компонент `PostControls` из стора передаю значение `const [setSearchValue] = useSearchValue()` .  Применяется здесь:
```javascript
...
<Input
    width='100%'
    placeholder={intl.formatMessage(messages.search)}
    onChange={event => setSearchValue(event.target.value)}
/>
...
```
значение `searchValue` из стора не передаю, т.к. оно в этом компоненте не используется, НО без этого значения перестал работать этот фильтр по поиску. 
Описание ошибки:
Uncaught TypeError: setSearchValue is not a function
    at onChange (PostControls.tsx:63)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)

Не могу самостоятельно понять, что не так.

**Comment by TFK70** [comment]
> @TFK70 в компонент `PostControls` из стора передаю значение `const [setSearchValue] = useSearchValue()` . Применяется здесь:
> 
> ```js
> ...
> <Input
>     width='100%'
>     placeholder={intl.formatMessage(messages.search)}
>     onChange={event => setSearchValue(event.target.value)}
> />
> ...
> ```
> 
> значение `searchValue` из стора не передаю, т.к. оно в этом компоненте не используется, НО без этого значения перестал работать этот фильтр по поиску.
> Описание ошибки:
> Uncaught TypeError: setSearchValue is not a function
> at onChange (PostControls.tsx:63)
> at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
> 
> Не могу самостоятельно понять, что не так.

useState всегда возвращает массив из 2 значений: переменную состояния и функцию. У тебя оттуда только переменная и берётся
То, что в её названии есть префикс set не делает её функцией

Чтобы пропустить первое значение, возвращаемое useState'ом можно сделать так:
```javascript
const [,setSearchValue] = useSearchValue()
```
