### ISSUE TITLE
[task] DOM. Actions with web page elements

### ISSUE THREAD

**Issue by ikorol3107** [Atlantis-Academy/frontend-study-ikorol#9]
**Основы JavaScript**

Задание:

- Удалить все рекламные блоки со страницы (правая часть сайта)

- Изменить жанр фильма, поменять "комедия" на "драма"

- Изменить задний фон постера с фильмом на изображение "bg.jpg". Оно лежит в папке img. Реализовать только при помощи JS

- Список фильмов на странице сформировать на основании данных из этого JS файла. Отсортировать их по алфавиту

- Добавить нумерацию выведенных фильмов

**Comment by TorinAsakura** [comment]
@ikorol3107 снова
