### ISSUE TITLE
[feature] create public package 

### ISSUE THREAD

**Issue by TFK70** [Atlantis-Academy/frontend-study-ikorol#90]
### С чем связан запрос на фичу?

1. Создать публичный пакет `@ikorol/list`, отвечающий за отрисовку TodoItem
2. Внедрить в проект, установив как зависимость

### Расскажите как вы это себе видите

Пакет должен быть публичным, т.е. присутствовать в [npm регистре](https://docs.npmjs.com/creating-and-publishing-scoped-public-packages)

Пакет будет заменять `@ui/list`, API не изменится
Сам `@ui/list` нужно будет убрать, за ненадобностью

Пример использования:

```javascript
import TodoList from '@ikorol/list'

<TodoList
      notes={notes}
      setNotes={setNotes}
      visibleNotes={filterNotes(notes, searchValue, filter)}
      deleteItem={deleteItem}
      toggleStatus={toggleStatus}
    />
```

### Приложите примеры реализаций

https://github.com/atls-academy/ikorol.github.io/tree/master/practice/my-diary/ui/list

**Comment by ikorol3107** [comment]
@TFK70 Читаю доку, понимаю, что в ui/list есть много зависимостей от других ui-компонентов, я же не могу их тянуть в публичный модуль. И тут я зависаю.. В какую сторону думать?

**Comment by TFK70** [comment]
@ikorol3107 Инициализируй их локально для твоего пакета, основное условие в том что он должен работать в изолированной среде

Кстати скинь содержимое package.json у пакета который собираешься паблить и его расположение

**Comment by ikorol3107** [comment]
@TFK70 package.json расположен в my-diary/ui/list

"name": "@ui/list",
  "version": "0.0.0",
  "license": "MIT",
  "main": "src/index.ts",
  "devDependencies": {
    "@types/styled-system": "^5.1.10"
  },
  "dependencies": {
    "react": "^17.0.1",
    "@emotion/styled": "^11.1.5",
    "styled-system": "^5.1.0",
    "@ui/button": "^0.0.0",
    "@ui/icons": "^0.0.0",
    "@ui/layout": "^0.0.0",
    "@ui/theme": "0.0.0",
    "@ui/text": "^0.0.0",
    "@store/notes": "0.0.0"

**Comment by ikorol3107** [comment]
@TFK70 Вот так должен выглядеть мой package.json в публичном пакете @academy/ikorol :
{
  "name": "@academy/ikorol",
  "version": "1.0.0",
  "license": "MIT",
  "main": "src/index.ts",
  "devDependencies": {
    "@types/styled-system": "^5.1.10"
  },
  "dependencies": {
    "react": "^17.0.1",
    "@emotion/styled": "^11.1.5",
    "styled-system": "^5.1.0"
  }
}

Структура пакета:
TodoList
-src
--index.ts
--Item.tsx
--List.tsx
-package.json

Использоваться пакет будет в PostList. 
Собственно не понимаю как вынести локальные зависимости, где я их потом буду инициализировать? в PostList ?

**Comment by TFK70** [comment]
> @TFK70 Вот так должен выглядеть мой package.json в публичном пакете @academy/ikorol :
> {
> "name": "@academy/ikorol",
> "version": "1.0.0",
> "license": "MIT",
> "main": "src/index.ts",
> "devDependencies": {
> "@types/styled-system": "^5.1.10"
> },
> "dependencies": {
> "react": "^17.0.1",
> "@emotion/styled": "^11.1.5",
> "styled-system": "^5.1.0"
> }
> }
> 
> Структура пакета:
> TodoList
> -src
> --index.ts
> --Item.tsx
> --List.tsx
> -package.json
> 
> Использоваться пакет будет в PostList.
> Собственно не понимаю как вынести локальные зависимости, где я их потом буду инициализировать? в PostList ?

1. Используй пожалуйста 
\`\`\`javascript
\*код\*
\`\`\`

2. Версия как и везде начинается с 0.0.0
3. Почему нельзя внутри него инициализировать все необходимые компоненты как [тут](https://github.com/atls/uikit/tree/master/ui-parts/select/src)? (включая иконки)

**Comment by ikorol3107** [comment]
@TFK70 "Почему нельзя внутри него инициализировать все необходимые компоненты как тут? (включая иконки)"

- тоесть внутри пакета @academy/ikorol еще делать папки button, icons, layout и тд? Пакет должен отвечать только за отрисовку TodoItem, не нарушит это принципы SOLID?

**Comment by TFK70** [comment]
> @TFK70 "Почему нельзя внутри него инициализировать все необходимые компоненты как тут? (включая иконки)"
> 
> * тоесть внутри пакета @academy/ikorol еще делать папки button, icons, layout и тд? Пакет должен отвечать только за отрисовку TodoItem, не нарушит это принципы SOLID?

А какие именно принципы это нарушает?

**Comment by ikorol3107** [comment]
@TFK70 думала про принцип единой ответственности, но теперь понимаю, что не нарушит это его.

**Comment by ikorol3107** [comment]
@TFK70 хочу протестировать свой пакет перед публикацией , запускаю npm install с полным путем к моему пакету и получаю ошибку:

**404 '@store/filter@0.0.0' is not in the npm registry. You should bug the author to publish it (or use the name yourself!)** 

@store/filter у меня находиться в package фрагмента postList куда я пытаюсь инсталировать пакет, а не в моем пакете. Он же по идее никак не должен влиять?

**Comment by TFK70** [comment]
> @TFK70 хочу протестировать свой пакет перед публикацией , запускаю npm install с полным путем к моему пакету и получаю ошибку:
> 
> **404 '@store/filter@0.0.0' is not in the npm registry. You should bug the author to publish it (or use the name yourself!)**
> 
> @store/filter у меня находиться в package фрагмента postList куда я пытаюсь инсталировать пакет, а не в моем пакете. Он же по идее никак не должен влиять?

А почему npm install? Мы с помощью npm только паблишим пакет

**Comment by TFK70** [comment]
@ikorol3107 https://classic.yarnpkg.com/en/docs/publishing-a-package/
create+publish

**Comment by ikorol3107** [comment]
@TFK70 с yarn тоже ошибка:-((
```javascript
irina@ikorol3107:~/WORK/ikorol.github.io/practice/todoList$ yarn publish
yarn publish v1.22.5
[1/4] Bumping version...
info Current version: 0.0.1
question New version: 0.0.1
[2/4] Logging in...
[3/4] Publishing...
error Couldn't publish package: "https://registry.yarnpkg.com/@academy%2fikorol: You must sign up for private packages"
info Visit https://yarnpkg.com/en/docs/cli/publish for documentation about this command.
```

**Comment by TFK70** [comment]
@ikorol3107 а почему у тебя пакет в practice находится?
Он должен находится вне твоих воркспейсов и никак с ними не связываться

**Comment by TFK70** [comment]
@ikorol3107 я говорил что ты можешь включить папку с пакетом как воркспейс для тестов, когда ты будешь его паблишить он должен быть полностью самостоятельным

**Comment by ikorol3107** [comment]
@TFK70 переместила пакет сюда: `irina@ikorol3107:~/WORK/todoList` , ошибка осталась такая же при попытке опубликовать.

**Comment by TFK70** [comment]
@ikorol3107 сделай коммит

**Comment by TFK70** [comment]
Closed by https://github.com/atls-academy/ikorol.github.io/pull/93
